global using Control.DAL.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Control.DAL.ModelsConfigurations;
global using System.Linq.Expressions;
global using Control.DAL.EF;
global using Control.DAL.Interfaces;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;